using System.Collections;
using System.Collections.Generic;
using UnityEngine;

public class CameraController : MonoBehaviour
{
    public float _FollowSpeeds = 5f;
    [SerializeField] private Transform _player;
    [SerializeField] private Transform _camTransform;

    public float _shakeDuration = 0f;

    public float _shakeAmount = 0.1f;
    public float _decreaseFactor = 1.0f;

    Vector3 _pos;

    private void Awake()
    {
    }

    void OnEnable()
    {
        _pos = _camTransform.localPosition;
    }
    public void ShakeCamera()
    {
        _pos = _camTransform.localPosition;
        _shakeDuration = 0.2f;
    }

    void Update()
    {
        Vector3 _newPosition = _player.position;
        _newPosition.z = -10f;
        transform.position = Vector3.Slerp(transform.position, _newPosition, _FollowSpeeds * Time.deltaTime);

        if (_shakeDuration > 0)
        {
            _camTransform.localPosition = _pos + Random.insideUnitSphere * _shakeAmount;

            _shakeDuration -= Time.deltaTime * _decreaseFactor;
        }
    }
}
